language: node_js
node_js:
  - "10"
os: linux
dist: trusty
deploy:
  provider: pages
  strategy: git
  cleanup: true
  local_dir: public
  token: $GITHUB_TOKEN
  keep_history: true
  target_branch: master
  on:
    branch: master
