language: node_js
before_script:
  - npm install -g gatsby
node_js:
  - "10"
os: linux
dist: trusty
deploy:
  provider: pages
  cleanup: true
  local_dir: public
  github-token: $GITHUB_TOKEN
  keep-history: true
  target_branch: master
  on:
    branch: master
