# This is the required part containing the build step for gatsby
language: node_js
node_js:
  - '12'
dist: trusty
os: linux
cache:
  npm: true
  directories:
    - public
    - .cache
script:
  - npm run build # Generate static HTML files

# Here is the magic part
deploy:
  strategy: git
  # Use Github pages deploy process
  provider: pages
  # Keep builded pages
  cleanup: true
  # Directory where your generated files are located
  local_dir: public
  # Github security/auth token
  token: $GITHUB_TOKEN
  # Incremental commit to keep old build/files from previous deployments
  keep_history: true
  # Git branch on which it should deploy (master, gh-pages, foo...)
  target_branch: gh-pages
  on:
    # Which branch on commit/push will trigger deployment
    branch: master
